import {setToken,readManifest,fileUrl,fetchFile} from './github.js';
const $=id=>document.getElementById(id);let files=[],current="",selected=new Set();
const size=n=>{if(!n)return"—";const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
function render(){const q=$("search").value.toLowerCase(),prefix=current?current+'/':'',dirs=new Set(),items=[];for(const f of files){if(!f.path.startsWith(prefix))continue;const rest=f.path.slice(prefix.length),p=rest.split('/');if(p.length>1){dirs.add(p[0]);continue}if(!q||f.path.toLowerCase().includes(q))items.push(f)}for(const d of [...dirs].sort())items.unshift({path:prefix+d,folder:true});$("crumbs").innerHTML=[''].concat(current.split('/').filter(Boolean)).map((v,i,a)=>'<span class="crumb" data-path="'+a.slice(0,i+1).join('/')+'">'+(v||'scripts box')+'</span>').join('');document.querySelectorAll('.crumb').forEach(x=>x.onclick=()=>{current=x.dataset.path;render()});$("entries").innerHTML=items.map(f=>f.folder?'<div class="entry folder"><span>📁</span><span class="name" data-folder="'+f.path+'">'+f.path.split('/').pop()+'/</span><span>文件夹</span><span>—</span></div>':'<div class="entry"><input type="checkbox" data-file="'+f.path+'" '+(selected.has(f.path)?'checked':'')+'><span class="name" data-file-name="'+f.path+'">'+f.path.split('/').pop()+'</span><span>'+(f.storage==='release'?'媒体':'Git')+'</span><span class="size">'+size(f.size)+'</span></div>').join('');document.querySelectorAll('[data-folder]').forEach(x=>x.onclick=()=>{current=x.dataset.folder;render()});document.querySelectorAll('[data-file]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.file):selected.delete(x.dataset.file);$("selected").textContent='已选 '+selected.size+' 项'});document.querySelectorAll('[data-file-name]').forEach(x=>x.onclick=()=>preview(files.find(f=>f.path===x.dataset.fileName)))}
const esc=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function preview(f){const p=$("preview");p.innerHTML='<h3>'+f.path.split('/').pop()+'</h3><p>'+(f.storage==='release'?'媒体文件':'Git 文件')+' · '+size(f.size)+'</p><button id="one">下载文件</button><div id="body">正在读取…</div>';const url=await fileUrl(f);$("one").onclick=()=>downloadRecord(f);const ext=f.path.split('.').pop().toLowerCase();if(['png','jpg','jpeg','gif','webp'].includes(ext))$("body").innerHTML='<img src="'+url+'" alt="">';else if(['mp4','webm','mov'].includes(ext))$("body").innerHTML='<video controls src="'+url+'"></video>';else if(['mp3','wav','ogg'].includes(ext))$("body").innerHTML='<audio controls src="'+url+'"></audio>';else if(f.size<2*1024*1024){try{$("body").innerHTML='<pre>'+esc(await (await fetchFile(f)).text())+'</pre>'}catch{$("body").textContent='无法预览，请下载文件'}}else $("body").textContent='文件较大，请下载后查看'}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;a.target='_blank';a.click()}async function downloadRecord(f){const blob=await (await fetchFile(f)).blob();download(URL.createObjectURL(blob),f.path.split('/').pop())}
async function zipFiles(chosen,name){if(!window.JSZip){$("status").textContent='ZIP 组件加载失败，请逐个下载';return}const zip=new JSZip();$("status").textContent='正在打包 '+chosen.length+' 个文件…';for(const f of chosen){const r=await fetchFile(f);zip.file(f.path,await r.blob())}const blob=await zip.generateAsync({type:'blob'});download(URL.createObjectURL(blob),name);$("status").textContent='已生成 '+name}
async function init(){try{const m=await readManifest();files=m.files||[];$("status").textContent='已读取 '+files.length+' 个云端文件';render()}catch(e){$("status").textContent='读取失败：'+e.message}}
$("refresh").onclick=init;$("download").onclick=async()=>{const c=files.filter(f=>selected.has(f.path));if(!c.length){$("status").textContent='请先勾选文件';return}if(c.length===1)return downloadRecord(c[0]);zipFiles(c,'scripts-box-selected.zip')};$("folder").onclick=()=>{const p=current?current+'/':'';zipFiles(files.filter(f=>f.path.startsWith(p)),(current.split('/').pop()||'scripts-box')+'.zip')};$("token").onclick=()=>$("tokenDialog").showModal();$("saveToken").onclick=()=>{setToken($("tokenInput").value);init()};$("search").oninput=render;$("theme").onclick=()=>document.body.classList.toggle('light');init();
